[package]
name = "cryptonote"
version = "0.10.0"
authors = ["Michael Bohn <spaceodyssey@gmx.de>"]

[lib]
name = "cryptonote"

[dependencies]
groestl = "0.9.0"
blake = "2.0.1"
blake2b_simd = "0.5.11"
jh-ffi = "0.5.0"
skein-ffi = "0.5.0"
serde = "1.0.125"
serde_json = "1.0.64"
serde_derive = "1.0.125"
strum = { version = "0.20.0", features = ["derive"] }
config = "0.11.0"
log = "0.4.14"
env_logger = "0.8.3"
num_cpus = "1.13.0"
bandit = "0.12.2"
byteorder = "1.4.3"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
dirs = "3.0.1"
crossbeam-channel = "0.5.0"
rust-argon2 = { git = "https://github.com/Ragnaroek/rust-argon2" }

[dev-dependencies]
difference = "2.0.0"
lazy_static = "1.4.0"